services:
  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - ./docker/pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: your-database-name # THIS MUST MATCH YOUR DB NAME IN .env
      POSTGRES_PASSWORD: your_password
      POSTGRES_HOST_AUTH_METHOD: trust
volumes:
  mysql_data:
  postgres_data:
